### ISSUE TITLE
Version 0.4.0 Release Checklist

### ISSUE THREAD

**Issue by bebleo** [bebleo/smtpdfix#144]
This is a reminder checklist to ensure that everything has been done before release 0.4.0 is published:

- [x] Bump versions in \requirements\latest to latest versions.
- [x] `__version__` updated to 0.4.0 in \smtpdfix\\\_\_init\_\_.py
- [x] Release date set in \docs\CHANGELOG.md

**Comment by bebleo** [comment]
Published release 0.4.0
