### ISSUE TITLE
Version 0.4.1 Release Checklist

### ISSUE THREAD

**Issue by bebleo** [bebleo/smtpdfix#229]
This is a reminder checklist to ensure that everything has been done before release 0.4.1 is published:

- [x] Bump versions in \requirements\latest to latest versions.
- [x] `__version__` updated to 0.4.1 in \smtpdfix\\\_\_init\_\_.py
- [x] Release date set in \docs\CHANGELOG.md
